services:
  - type: web
    name: my-django-app
    env: python
    buildCommand: >
      pip install -r requirements.txt &&
      python manage.py collectstatic --noinput &&
      python manage.py migrate &&
      python manage.py loaddata category good user
    startCommand: pipenv run gunicorn anime_shop_online.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: anime_shop_online.settings