# Generated by Django 5.2.4 on 2025-07-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='cloudinary_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
