# Generated by Django 5.2.1 on 2025-06-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_goods_cropping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
