# Generated by Django 5.1.2 on 2025-05-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('man', 'Man'), ('gril', 'Gril'), ('other', 'Other'), ('no_info', 'No Info')], default='no info', max_length=30),
        ),
    ]
