# Generated by Django 5.1.2 on 2025-05-15 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_basket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='goood',
            new_name='good',
        ),
    ]
