# Generated by Django 5.2.1 on 2025-05-24 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_delete_cart'),
        ('user', '0004_rename_goood_basket_good'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveGood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.goods')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
