# Generated by Django 5.2.1 on 2025-05-28 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_delete_cart'),
        ('user', '0005_savegood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savegood',
            name='good',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.goods'),
        ),
    ]
