# Generated by Django 5.2.3 on 2025-07-06 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
        ('shop', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='goods',
            field=models.ManyToManyField(related_name='order_goods', through='order.OrderGood', to='shop.good'),
        ),
    ]
