# Generated by Django 5.2.3 on 2025-07-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_user'),
        ('shop', '0005_alter_goods_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='goods',
        ),
        migrations.AddField(
            model_name='order',
            name='goods',
            field=models.ManyToManyField(to='shop.goods'),
        ),
    ]
